[pytest]

# params for tests
addopts =
    -v
    -s
    --maxfail=20
    --disable-warnings
    --capture=no
    --cache-clear
    --tb=short
    --clean-alluredir
    --alluredir=allure-results



markers =
    smoke: Smoke test
    regression: Regression test
    critical: Critical test
    slow: Slow test
    ui: UI test
    api: API test
    only: marks tests to be run exclusively
    inv: not valid promo
    valid: valid promo code
    period_plan: switches to periods and plans
    filling_out_card: filling out card with data
    alerts: dealing with alerts
    usual_click: click on element
    js_click: click with JS
    action_chains_click: action chains click
    send_keys_click: send keys click
    iframe: dealing with iframe
    input: dealing with input
    upload: uploading file
    download: downloading file
    windows: dealing with windows


[tool:pytest]
allure_html_report = True
allure_serving = True
