[pytest]
markers =
    only: marks tests to be run exclusively
    inv: not valid promo
    valid: valid promo code
    period_plan: switches to periods and plans
    filling_out_card: filling out card with data
